// toggleActions:
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const OPEN_EDIT_SIDEBAR = 'OPEN_EDIT_SIDEBAR';
export const CLOSE_EDIT_SIDEBAR = 'CLOSE_EDIT_SIDEBAR';
export const OPEN_NEW_SIDEBAR = 'OPEN_NEW_SIDEBAR';
export const CLOSE_NEW_SIDEBAR = 'CLOSE_NEW_SIDEBAR';
export const TOGGLE_DELETION = 'TOGGLE_DELETION';

// formActions
export const HANDLE_SENDER_INFO = 'HANDLE_SENDER_INFO';
export const HANDLE_CLIENT_INFO = 'HANDLE_CLIENT_INFO';
export const HANDLE_GENERAL_INFO = 'HANDLE_GENERAL_INFO';
export const HANDLE_DATE_INFO = 'HANDLE_DATE_INFO';
export const HANDLE_TERM_INFO = 'HANDLE_TERM_INFO';
export const HANDLE_ITEM_INFO = 'HANDLE_ITEM_INFO';
export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET_ITEM = 'SET_ITEM';
export const RESET_ITEM = 'RESET_ITEM';

// dataActions
export const START_FETCH = 'START_FETCH';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const GET_SINGLE_ITEM = 'GET_SINGLE_ITEM';
