// toggleActions:
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const OPEN_EDIT_SIDEBAR = 'OPEN_EDIT_SIDEBAR';
export const CLOSE_EDIT_SIDEBAR = 'CLOSE_EDIT_SIDEBAR';
export const OPEN_NEW_SIDEBAR = 'OPEN_NEW_SIDEBAR';
export const CLOSE_NEW_SIDEBAR = 'CLOSE_NEW_SIDEBAR';
export const TOGGLE_DELETION = 'TOGGLE_DELETION';

// formActions
export const HANDLE_SENDER_INFO = 'HANDLE_SENDER_INFO';
export const HANDLE_CLIENT_INFO = 'HANDLE_CLIENT_INFO';
export const HANDLE_GENERAL_INFO = 'HANDLE_GENERAL_INFO';
export const HANDLE_DATE_INFO = 'HANDLE_DATE_INFO';
export const HANDLE_TERM_INFO = 'HANDLE_TERM_INFO';
export const HANDLE_ITEM_INFO = 'HANDLE_ITEM_INFO';
export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const SET_ITEM = 'SET_ITEM';
export const RESET_ITEM = 'RESET_ITEM';

// dataActions
export const START_FETCH = 'START_FETCH';
export const ERROR_FETCH = 'ERRPR_FETCH';
export const GET_ALL_INVOICES = 'GET_ALL_INVOICES';
export const GET_SINGLE_INVOICE = 'GET_SINGLE_INVOICE';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const CREATE_INVOICE = 'CREATE_INVOICE';

// userActions
export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
